### PR TITLE
TRIVIAL: add TypeScript definitions

### PR DESCRIPTION
**Pull request by mrmlnc**
#### What is the purpose of this pull request?

This is the finished version of #17.

### CODE REVIEW

**Comment by mrmlnc** [comment]
CI is broken in this repository for Node.js below 4 ¯\\_(ツ)_/¯

**Comment by Scrum** [comment]
> CI is broken in this repository for Node.js below 4 ¯\(ツ)/¯

@mrmlnc You can drop everything below

**Comment by Scrum** [comment]
@mrmlnc @voischev ping ?

**Comment by mrmlnc** [comment]
LGTM

**Comment by Scrum** [comment]
LGTM

**Comment by mrmlnc** [comment]
Merged with administrative privileges.

**Pull request merged**
